[package]
name = "card_game"
version = "0.1.0"
authors = ["Ivica Munitic <imunitic@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.9.3"
# gdnative = { path = "../../godot-rust/gdnative" }
